version: "3.9"
services:
  # web:
  #   build: .
  #   ports:
  #     - "${EXPRESS_PORT}:${EXPRESS_PORT}"
  #   environment:
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_PORT=${POSTGRES_PORT}
  postgres:
    image: "postgres:alpine"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"